In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
cd drive/MyDrive/NLP\ problems

/content/drive/MyDrive/NLP problems

In [4]:
import pandas as pd
train = pd.read_csv('Airline Booking.csv')
train.head()

    ID  ... Unnamed: 95
0  1.0  ...         NaN
1  2.0  ...         NaN
2  3.0  ...         NaN
3  4.0  ...         NaN
4  5.0  ...         NaN

[5 rows x 96 columns]

In [5]:
train.drop(train.iloc[:,2:],inplace = True,axis = 1)

In [6]:
train.drop('ID',axis=1)

                                            Description
0     Cheap Flights to Hong Kong (HKG) from $394 - K...
1     $480 Flights to Hong Kong, China (HKG) - TripA...
2     Cheap Flights to Hong Kong International from ...
3     Flights to Hong Kong (HKG) | Hong Kong Flight ...
4     Cheap Flights to Hong Kong SAR, Asia $184 in 2...
...                                                 ...
3246                                                NaN
3247                                                NaN
3248                                                NaN
3249                                                NaN
3250                                                NaN

[3251 rows x 1 columns]

In [7]:
train.dropna(axis = 0,inplace=True)

In [8]:
train['Description'][1]

'$480 Flights to Hong Kong, China (HKG) - TripAdvisor'

In [9]:
raw_string = ""
for ind in train.index:
  raw_string = raw_string + train['Description'][ind] + ". "

In [10]:
print(raw_string)

Cheap Flights to Hong Kong (HKG) from $394 - KAYAK. $480 Flights to Hong Kong, China (HKG) - TripAdvisor. Cheap Flights to Hong Kong International from $382 in 2019 .... Flights to Hong Kong (HKG) | Hong Kong Flight Deals | Cathay Pacific. Cheap Flights to Hong Kong SAR, Asia $184 in 2019 | Expedia. Cheap Flights to Hong Kong - Search Deals on Airfare to Hong .... Flights to Hong Kong SAR (HKG) on Orbitz.com. Passenger Arrivals, Flights - Hong Kong International Airport. Fly Hong Kong Airlines | Flights To & From Hong Kong| Airfare. Find Cheap Flights to Hong Kong from 400 USD | momondo. $454 Flights to Bangkok, Thailand (BKK) - TripAdvisor. Cheap Flights to Bangkok, Bangkok $376 in 2019 | Expedia. Find Cheap Flights to Bangkok Suvarnabhumi & other airports (BKK). Cheap Flights to Bangkok from $398 - Skyscanner. Cheap Flights to Bangkok, Thailand - Search Deals on Airfare to .... Cheap Flights To Bangkok Thailand | CheapOair. Flights to Bangkok (BKK) on Orbitz.com. Flights to Bangkok, Thailand : Best Fare Guarantee on Plane Tickets .... United Cheap Flights to Bangkok | Flight Deals to (BKK) | United .... Flights to Bangkok (BKK) | Find and book flights to Bangkok .... Cheap Flights to London (LON) from $289 - KAYAK. $337 Flights to London, United Kingdom (LON) - TripAdvisor. Cheap Flights to London from £19 in 2019 | Skyscanner. Cheap Flights to London from $304 in 2019 | Skyscanner. Cheap Flights to London, England (LHR Airport) $79 in 2018 | Expedia. Cheap Flights to London, (LON) Airline Tickets. Flights to London (LON) $410+ | Direct Flights to {destination.name .... Deal Alert: Nonstop Flights to London From $369 Round-Trip. Cheap Flights to London (LHR) | Icelandair. Flights to London (LON) from €9 with eDreams!. Cheap Flights to Singapore (SIN) from $384 - KAYAK. Cheap Flights to Singapore, Singapore (SIN Airport) $460 in 2018 .... Cheap Flights to Singapore Changi From RM207 | Skyscanner .... $487 Flights to Singapore, Singapore (SIN) - TripAdvisor. Singapore Airlines Official Website | Book International Flight Tickets. Cheap Flights to Singapore Changi from $360 in 2019 | Skyscanner. Cheap Flights to Singapore - Find Airfares to Singapore. Cheap Flights to Singapore Changi from £308 | Skyscanner. Discount Flights to Singapore | AirAsia. Cheap Flights to Singapore - Search Deals on Airfare to Singapore .... Cheap Flights to Macau (MFM) from $404 - KAYAK. Cheap Flights to Macau SAR, Asia $158 in 2019 | Expedia. $464 Flights to Macau, China (MFM) - TripAdvisor. Cheap Flights to Macau. Cheap Flights to Macau from £438 | Skyscanner. Cheap flights to Macau from P1,502! Cheap Macau Flights .... Flights to Macau, Cheap Flights to Macau, Macau Air Tickets .... Save on flights to Macau from $455. Compare and book. Flights from Macau with Skyscanner. Cheap Flights to Macau SAR – C$539: Get Tickets Now | Expedia.ca. $367 Flights to Dubai, United Arab Emirates (DXB) - TripAdvisor. Cheap Flights to Dubai (DXB) from $496 - KAYAK. Flights to Dubai (DXB) | Find and book flights to Dubai | Emirates .... Cheap Flights to Dubai from $477 in 2019 | Skyscanner. Cheap Flights to Dubai, United Arab Emirates (DXB & DWC Airports .... Cheap Flights to Dubai from £208 | Skyscanner. Cheap Flights to Dubai, United Arab Emirates - Search Deals on .... Cheap Flights To Dubai | CheapOair. Flights to Dubai (DXB) on Orbitz.com. Cheap Flights to Dubai| Cheapest Flight From Lagos to Dubai .... Cheap Flights to Paris (PAR) from $257 - KAYAK. $297 Flights to Paris, France (PAR) - TripAdvisor. Cheap Flights to Paris, Ile-de-France (CDG Airport) $67 in 2018 .... Cheap Flights to Paris, France - Search Deals on Airfare to Paris .... Cheap Flights to Paris from $235 in 2019 | Skyscanner. Cheap Flights to Paris | CheapOair. Flight to Paris - Cheap flights to France | Air France USA. $404 + Flights to Paris (PAR) on Orbitz.com. Cheap Flights to Paris from $15 | JETCOST. Cheap Paris Flights, 2019 PAR Airfare @ $374 | Travelocity. Cheap Flights to New York (NYC) from $83 - KAYAK. $53 Flights to New York City, New York (NYC) - TripAdvisor. Cheap Flights to New York, New York $100 in 2019 | Expedia. Cheap Flights to New York, New York (NY) - Search Deals on .... Book Cheap Flights To New York City. Cheap Flights to New York from $79 in 2019 | Skyscanner. Cheap flights to New York City, NY (NYC) | priceline.com. Cheap Flights to New York City from $16 | JETCOST. Flights to New York (NYC) $100+ | Direct Flights to {destination .... $118+ Cheap Flights to New York (NYC): Book Cheap New York .... Cheap Flights to Shenzhen (SZX) from $333 - KAYAK. Cheap Flights to Shenzhen, Guangdong $121 in 2019 | Expedia. Cheap Flights to Shenzhen Bao'an International from £331 .... Cheap Flights to Shenzhen, China - Search Deals on Airfare to .... $457 Flights to Shenzhen, China (SZX) - TripAdvisor. Cheap Flights to Shenzhen Bao'an International From $239 .... Cheap Flights to Shenzhen, China (SZX) @ ₹ 32,041 - TripAdvisor. Cheap Flights to Shenzhen from £62 | JETCOST. Cheap Flights To Shenzhen: The Best Prices – Travelstart.co.za. Singapore to Shenzhen: Cheap flights to Shenzhen from Singapore .... Cheap Flights to Kuala Lumpur Intl (KUL) from $360 - KAYAK. Cheap Flights to Kuala Lumpur from £391 in 2019 | Skyscanner. $473 Flights to Kuala Lumpur, Malaysia (KUL) - TripAdvisor. Cheap Flights to Kuala Lumpur from $342 in 2019 | Skyscanner. Cheap Flights to Kuala Lumpur, Selangor (KUL Airport) $369 in .... Cheap Flights to Kuala Lumpur, Malaysia - Search Deals on Airfare .... Cheap Flights to Kuala Lumpur Intl (KUL) from £301 - KAYAK. Cheap Flights to Kuala Lumpur - Widest Choice & 24/7 Care. Cheap Flights to Kuala Lumpur From $44 | Skyscanner Singapore. Cheap Flights to Kuala Lumpur, Malaysia - Webjet. $453 Flights to Phuket, Thailand (HKT) - TripAdvisor. Cheap Flights to Phuket, Phuket (HKT Airport) $428 in 2018 | Expedia. Cheap Flights to Phuket City (HKT) from $399 - KAYAK. Cheap Flights to Phuket from $390 in 2019 | Skyscanner. Flights to Phuket. Save on flights to Phuket from $282. Compare and book. Flights to Phuket (HKT) | Book now with British Airways. Cheap Flights to Phuket from £271 | Skyscanner. Cheap Flights to Phuket, Thailand - Search Deals on Airfare to .... Cheap Flights to Phuket, Thailand - Webjet. Cheap Flights to New Delhi (DEL) from $375 - KAYAK. Cheap Flights to Delhi, Uttar Pradesh (DEL Airport) $393 in 2018 .... Cheap Flights to New Delhi from $367 in 2019 | Skyscanner. Cheap Flights to New Delhi from £287 | Skyscanner. $483 Flights to New Delhi, India (DEL) - TripAdvisor. Cheap Flights to Delhi, India - Search Deals on Airfare to Delhi from .... Flights to Delhi (DEL) from $ 664 | Flights offers - Lufthansa ®. Cheap Flights to Delhi from $485 - Cheapflights.com.au. Flights to Delhi from US$ 474 | Vayama. Flights to New Delhi, Flat 30% Cashback on New Delhi Air Tickets. Cheap Flights to Tokyo (TYO) from $368 - KAYAK. $478 Flights to Tokyo, Japan (TYO) - TripAdvisor. Cheap Flights to Tokyo, Tokyo (HND Airport) $363 in 2018 | Expedia. Cheap Flights to Tokyo from $367 in 2019 | Skyscanner. $807 + Flights to Tokyo (TYO) on Orbitz.com. Cheap Flights to Tokyo, Japan - Search Deals on Airfare to Tokyo .... Cheap Flights to Tokyo, (TYO) Airline Tickets. Cheap Flights to Tokyo from £411 in 2019 | Skyscanner. Cheap Flights to Tokyo From RM992 | Skyscanner Malaysia. Sydney (SYD) to Tokyo (HND) Flights | Qantas AU. Cheap Flights to Rome (ROM) from $327 - KAYAK. $331 Flights to Rome, Italy (ROM) - TripAdvisor. Cheap Flights to Rome, Lazio (FCO Airport) $60 in 2018 | Expedia. Cheap Flights to Rome from $293 in 2019 | Skyscanner. Cheap Flights to Rome, Italy - Search Deals on Airfare to Rome from .... Cheap Flights to Rome. Flights to Rome - moovel lab. Flights to Rome (ROM) from $ 350 | Flights offers - Lufthansa ®. Cheap Rome Flights, 2019 ROM Airfare @ $326 | Travelocity. Cheap Flights to Rome from £30 in 2019 | Skyscanner. Cheap Flights to Taipei, Taiwan (TPE & TSA Airports) $201 in 2018 .... Cheap Flights to Taipei Taiwan Taoyuan Intl & other Airports (TPE .... $463 Flights to Taipei, Taiwan (TPE) - TripAdvisor. Cheap Flights to Taipei from $384 in 2019 | Skyscanner. Flights to Taipei (TPE) | Taipei Flight Deals | Cathay Pacific. Cheap Flights to Taipei From $198 | Skyscanner Singapore. Book flights to Taipei (TPE) | Singapore Airlines. Cheap Flights to Taipei From RM455 | Skyscanner Malaysia. $412 + Flights from Los Angeles (LAX) to Taipei (TPE) on Orbitz.com. Cheap Flights to Taipei from £414 in 2019 | Skyscanner. Cheap Flights to Guangzhou, Guangdong $348 in 2019 | Expedia. Cheap Flights to Guangzhou (CAN) from $322 - KAYAK. $443 Flights to Guangzhou, China (CAN) - TripAdvisor. Cheap Flights to Guangzhou, China - Search Deals on Airfare to .... Cheap Flights to Guangzhou from $356 in 2019 | Skyscanner. Cheap Flights to Guangzhou from £331 | Skyscanner. Cheap Flights to Guangzhou From RM249 | Skyscanner Malaysia. Save on flights to Guangzhou from $345. Compare and book. Cheap Flights to Guangzhou AU$358 in 2018 - Book Now | Expedia. Cheap Flights to Guangzhou from R8293 - Cheapflights.co.za. Cheap Flights to Mumbai (BOM) from $494 - KAYAK. Cheap Flights to Mumbai, Maharashtra (BOM Airport) $507 in 2018 .... Cheap Flights to Mumbai from $438 in 2019 | Skyscanner. $506 Flights to Mumbai, India (BOM) - TripAdvisor. Cheap Flights to Mumbai, India - Search Deals on Airfare to Mumbai .... Cheap Flights to Mumbai, (BOM) Airline Tickets. Cheap Flights to Mumbai (Bombay) - Lowest fare Guaranteed at .... Cheap Flights to Mumbai from R5067 - Cheapflights.co.za. Flights to Mumbai (BOM) from $ 676 | Flights offers - Lufthansa ®. Cheap Flights to Mumbai from £309 | Skyscanner. Cheap Flights to Mecca, Saudi Arabia $242 in 2019 | Expedia. 5 Cheap Flights to Mecca, Saudi Arabia - TripAdvisor. Cheap Flights to Mecca (JED) from £304 - ebookers.com. Flights to Mecca (JED Airport) | Expedia. Cheap Mecca Flights, 2019 JED Airfare @ $881 | Travelocity. Cheap Flights to Makkah | Book Flights to Makkah Online - tajawal. Cheap Flights to Mecca – C$1,042: Get Tickets Now | Expedia.ca. Flights to Mecca (JED) on Orbitz.com. Cheap Flights to Mecca from RM1,840, Compare and Book the .... Cheap Flights to Mecca, Book the Cheapest Flight to Mecca, Saudi .... $509 Flights to Istanbul, Turkey (IST) - TripAdvisor. Cheap Flights to Istanbul, Turkey $509 in 2019 | Expedia. Cheap Flights to Istanbul from $446 in 2019 | Skyscanner. Cheap Flights to Istanbul Ataturk & other airports (IST) - KAYAK. Flights to İstanbul | Turkish Airlines ® | City Guide. Cheap Flights to Istanbul, Turkey - Search Deals on Airfare to .... Find Cheap Flights to Istanbul from 492 USD | momondo. Cheap Flights to Istanbul From RM2,225 | Skyscanner Malaysia. Flights to Istanbul, Turkey : Best Fare Guarantee on Plane Tickets .... Cheap flights to Istanbul from £32 - Book trips to Istanbul, Turkey .... Cheap Flights to Prague (PRG) from $371 - KAYAK. Cheap Flights to Prague from $386 in 2019 | Skyscanner. Cheap Flights to Prague, Prague (PRG Airport) $74 in 2018 | Expedia. $426 Flights to Prague, Czech Republic (PRG) - TripAdvisor. Flight Information | Vaclav Havel Airport Prague, Ruzyne. Cheap Flights to Prague from £27 | Skyscanner. Flights to Prague (PRG) from $ 575 | Flights offers - Lufthansa ®. easyJet.com | Cheap winter flights to Prague for £23.16 or less. Cheap flights to Prague from $42 | Skyscanner Israel. Flights from Prague with Skyscanner. Cheap Flights to Miami (MIA) from $56 - KAYAK. Cheap Flights to Miami, Florida (MIA Airport) $56 in 2018 | Expedia. $97 Flights to Miami, Florida (MIA) - TripAdvisor. Cheap Flights to Miami, Florida (FL) - Search Deals on Airfare to .... $61 Flights to Miami (MIA) in 2019 | Hotwire. Cheap Flights to Miami from $55 in 2019 | Skyscanner. Cheap Flights to Miami from $23 | JETCOST. $132 + Flights to Miami (MIA) on Orbitz.com. Cheap Flights to Miami | CheapOair. Cheap flights to Miami, FL (MIA) | priceline.com. $455 Flights to Seoul, South Korea (SEL) - TripAdvisor. Cheap Flights to Seoul (SEL) from $361 - KAYAK. $923 + Flights to Seoul (SEL) on Orbitz.com. Cheap Flights to Seoul, Gyeonggi (ICN Airport) $196 in 2018 | Expedia. Cheap Flights to Seoul from $334 in 2019 | Skyscanner. Cheap Flights to Seoul, South Korea - Search Deals on Airfare to .... Cheap Flights to Seoul From RM932 | Skyscanner Malaysia. Flights to Seoul, Korea : Best Fare Guarantee on Plane Tickets : Delta. Cheap Flights to Seoul from £374 in 2019 | Skyscanner. Cheap Flights to Seoul | StudentUniverse. $327 Flights to Barcelona, Spain (BCN) - TripAdvisor. Cheap Flights to Barcelona-El Prat (BCN) from $255 - KAYAK. Cheap Flights to Barcelona from $244 in 2019 | Skyscanner. Cheap Flights to Barcelona, Catalonia (BCN Airport) $328 in 2018 .... Cheap Flights To Barcelona | CheapOair. Cheap Flights to Barcelona from £23 | Skyscanner. Cheap Flights to Barcelona from USA and Canada | WOW air. Flights to Barcelona (BCN) from $ 331 | Flights offers - Lufthansa ®. easyJet.com | Cheap winter flights to Barcelona for £22.49 or less. Flights to Barcelona - Wizz Air. $371 Flights to Pattaya, Thailand - TripAdvisor. Cheap Flights to Pattaya, Chonburi $125 in 2019 | Expedia. Cheap Flights to Pattaya (Chonburi) from £492 | Skyscanner. Cheap Flights to Pattaya (BKK) from £308 - ebookers.com. Cheap Flights to Pattaya (UTP) - Search Deals on Airfare to Pattaya .... Cheap Flights to Pattaya, Thailand @ ₹ 33,681 - TripAdvisor. $454 Flights to Pattaya (BKK) in 2019 | Hotwire. Airlines That Fly to Pattaya (Chonburi), UTP | Skyscanner. Cheap Flights to Pattaya, Book the Cheapest Flight to Pattaya .... Flights to Pattaya | Expedia. Cheap Flights to Shanghai, China $153 in 2019 | Expedia. Cheap Flights to Shanghai Pu Dong (PVG) from $349 - KAYAK. $407 Flights to Shanghai, China (SHA) - TripAdvisor. Cheap Flights to Shanghai from $317 in 2019 | Skyscanner. Cheap Flights to Shanghai from $121 round trip (SHA) - FareCompare. Cheap Flights to Shanghai Pu Dong, (PVG) Airline Tickets. Flights to Shanghai, China : Best Fare Guarantee on Plane Tickets .... Cheap Flights to Shanghai, China - Search Deals on Airfare to .... Flights to Shanghai (SHA) on Orbitz.com. Cheap Flights to Shanghai From RM659 | Skyscanner Malaysia. Cheap Flights to Milan (MIL) from $348 - KAYAK. $438 Flights to Milan, Italy (MIL) - TripAdvisor. Cheap Flights to Milan from $333 in 2019 | Skyscanner. Cheap Flights to Milan, Lombardy (MXP Airport) $57 in 2018 | Expedia. Cheap Flights to Milan from £23 in 2019 | Skyscanner. Flights. Flights to Milan (MIL) from $ 447 | Flights offers - Lufthansa ®. Cheap Flights to Milan, Italy - Search Deals on Airfare to Milan from .... Cheap Flights to Milan, (MIL) Airline Tickets. Flights to Milan (MXP) | Emirates United States. Cheap Flights to Cancún (CUN) from $144 - KAYAK. $217 Flights to Cancun, Mexico (CUN) - TripAdvisor. Cheap Flights to Cancun, Quintana Roo (CUN Airport) $145 in 2018 .... Cheap Flights to Cancun, Mexico - Search Deals on Airfare to .... Cheap Flights to Cancun from $143 in 2019 | Skyscanner. $226 Flights to Cancun (CUN) in 2019 | Hotwire. Flights to Cancun (CUN) starting from $42 USD | Interjet. Flights to Cancun (CUN) $242+ | Direct Flights to {destination.name .... Book Flights to Cancun CUN | Spirit Airlines. Book cheap flights to Cancun (CUN) with Volaris from USD 139. Flights to Agra, Flat 30% Cashback on Agra Air Tickets. Cheap Flights to Agra District, Uttar Pradesh $393 in 2019 | Expedia. Flights to Agra | Cheap Air Tickets to Agra @ ₹1656 - Yatra.com. Airlines that fly to Agra. 5 Cheap Flights to Agra, India (AGR) - TripAdvisor. Flights to Agra from ₹ 1,199! Cheap Agra Flights @Skyscanner IN. Cheap Flights to Agra from £18 | JETCOST. Flights to and From Agra | Maps of Agra. Cheap Flights to Agra, India (AGR) @ ₹ 3,359 - TripAdvisor. Book Agra to Mumbai Flights @ ₹4763 + ₹1000 off. Cheap Flights to Las Vegas (LAS) from $57 - KAYAK. Cheap Flights to Las Vegas, Nevada (LAS Airport) $75 in 2018 .... $150 Flights to Las Vegas, Nevada (LAS) - TripAdvisor. $162 Flights to Las Vegas (LAS) in 2019 | Hotwire. Cheap Flights to Las Vegas, Nevada (NV) - Search Deals on Airfare .... Flights to Las Vegas (LAS) $152+ | Direct Flights to {destination .... Cheap Flights to Las Vegas | CheapOair. Tips For Finding Cheap Flights To Las Vegas. Discount Las Vegas Flights & Vacation Packages | Vegas.com. Cheap Flights to Las Vegas from $23 | JETCOST. Cheap Flights to Amsterdam (AMS) from $299 - KAYAK. Cheap Flights to Amsterdam from $273 in 2019 | Skyscanner. $332 Flights to Amsterdam, The Netherlands (AMS) - TripAdvisor. Cheap Flights to Amsterdam, North Holland (AMS Airport) $53 in .... Cheap Flights to Amsterdam, Netherlands - Search Deals on Airfare .... Cheap Flights to Amsterdam from USA and Canada | WOW air. Cheap Flights to Amsterdam, (AMS) Airline Tickets. Cheap Flights to Amsterdam from £55 | Skyscanner. Schiphol | Search and find Amsterdam Airport Schiphol departures. easyJet.com | Cheap winter flights to Amsterdam for £22.99 or less. Cheap Flights to Antalya, Turkey (AYT Airport) $129 in 2018 | Expedia. Cheap Flights to Antalya from £75 | Skyscanner. easyJet.com | Cheap winter flights to Antalya for £49.42 or less. Cheap Flights to Antalya (AYT) from $540 - KAYAK. Flights to Antalya 2018/19 - Fly Thomas Cook Airlines. Cheap Flights to Antalya from $445 in 2019 | Skyscanner. Cheap Flights to Antalya (AYT) from £96 - KAYAK. Cheap flights to Antalya from £38 - Book trips to Antalya, Turkey with .... Cheap Flights to Antalya (AYT) | Jet2.com. Flights to Antalya | Cheap Antalya flights | lastminute.com. Cheap Flights to Denpasar (DPS) from $429 - KAYAK. Cheap Flights to Bali from $319 in 2019 | Skyscanner. Flight Status – Arrivals | Departures – Bali Airport Guide. Save on flights to Bali (Denpasar) from $219. Compare and book. Cheap Flights to Bali (Denpasar) from £434 | Skyscanner. $445 Flights to Denpasar, Indonesia (DPS) - TripAdvisor. Cheap Flights to Bali from $236 - Cheapflights.com.au. Cheap Flights To Denpasar: Compare All Airlines – Travelstart.co.za. Cheap Flights to Bali | Jetstar. Cheap Flights to Denpasar (DPS) from C$ 691 - KAYAK. Cheap Flights to Osaka, Osaka (KIX & ITM Airports) $175 in 2018 .... Cheap Flights to Osaka Kansai International (KIX) from $199 - KAYAK. $493 Flights to Osaka, Japan (OSA) - TripAdvisor. Cheap Flights to Osaka (OSA) from $199 - KAYAK. Cheap Flights to Osaka from $384 in 2019 | Skyscanner. Cheap Flights to Osaka, Japan - Search Deals on Airfare to Osaka .... Cheap Flights to Osaka From RM1,023 | Skyscanner Malaysia. Book flights to Osaka, Japan (KIX) | Singapore Airlines. Cheap Flights to Osaka from £376 in 2019 | Skyscanner. Save on flights to Osaka from $465. Compare and book now. Cheap Flights to Los Angeles (LAX) from $79 - KAYAK. Cheap Flights to Los Angeles, California (LAX Airport) $75 in 2018 .... $206 Flights to Los Angeles, California (LAX) - TripAdvisor. Cheap Flights to Los Angeles from $23 | JETCOST. $202 Flights to Los Angeles (LAX) in 2019 | Hotwire. $202 + Flights to Los Angeles (QLA) on Orbitz.com. Cheap Flights to Los Angeles (LAX) from $62 in 2019 | Skyscanner. $209+ Cheap Flights to Los Angeles (QLA): Book Cheap Los .... Flights from Los Angeles | All destinations | Norwegian. Book Cheap Flights To Los Angeles. Cheap Flights to Vienna, Vienna (VIE Airport) $378 in 2018 | Expedia. Cheap Flights to Vienna (VIE) from $319 - KAYAK. Cheap Flights to Vienna from $342 in 2019 | Skyscanner. $336 Flights to Vienna, Austria (VIE) - TripAdvisor. Flights to Vienna (VIE) from $ 521 | Flights offers - Lufthansa ®. Cheap Flights to Vienna from £19 | Skyscanner. Cheap Flights to Vienna, Austria - Search Deals on Airfare to Vienna .... Flight to Vienna (VIE) from €19.99* - Eurowings. Viennaairport - Arrival / Departure. Cheap flights to Vienna VIE from 79 £ - Austrian Airlines® (OS). Cheap Flights to Berlin (BER) from $300 - KAYAK. $367 Flights to Berlin, Germany (BER) - TripA

In [20]:
import spacy

spacy_nlp = spacy.load('en')
document = spacy_nlp(raw_string)

In [21]:
for element in document.ents:
    print('Type: %s, Value: %s' % (element.label_, element))

Type: GPE, Value: Hong Kong
Type: ORG, Value: HKG
Type: MONEY, Value: $394
Type: MONEY, Value: 480
Type: GPE, Value: Hong Kong
Type: GPE, Value: China
Type: MONEY, Value: 382
Type: DATE, Value: 2019
Type: GPE, Value: Hong Kong
Type: GPE, Value: Hong Kong
Type: PERSON, Value: Cathay Pacific
Type: GPE, Value: Hong Kong SAR
Type: LOC, Value: Asia
Type: DATE, Value: 2019
Type: GPE, Value: Hong Kong
Type: GPE, Value: Hong
Type: GPE, Value: Hong Kong SAR
Type: ORG, Value: Orbitz.com
Type: ORG, Value: Flights - Hong Kong International Airport
Type: ORG, Value: Hong Kong Airlines
Type: GPE, Value: Hong Kong
Type: CARDINAL, Value: 400
Type: MONEY, Value: 454
Type: GPE, Value: Bangkok
Type: GPE, Value: Thailand
Type: GPE, Value: Bangkok
Type: GPE, Value: Bangkok
Type: MONEY, Value: 376
Type: DATE, Value: 2019
Type: ORG, Value: Bangkok Suvarnabhumi & other
Type: GPE, Value: Bangkok
Type: MONEY, Value: 398
Type: GPE, Value: Bangkok
Type: GPE, Value: Thailand
Type: GPE, Value: Bangkok
Type: ORG, Value: Orbitz.com
Type: GPE, Value: Bangkok
Type: GPE, Value: Thailand
Type: GPE, Value: Plane Tickets
Type: PERSON, Value: United
Type: PERSON, Value: Bangkok
Type: GPE, Value: Bangkok
Type: GPE, Value: London
Type: ORG, Value: LON
Type: MONEY, Value: 289
Type: MONEY, Value: 337
Type: GPE, Value: London
Type: GPE, Value: United Kingdom
Type: ORG, Value: LON
Type: WORK_OF_ART, Value: Flights to London
Type: MONEY, Value: 19
Type: DATE, Value: 2019
Type: PERSON, Value: | Skyscanner
Type: WORK_OF_ART, Value: Flights to London
Type: MONEY, Value: 304
Type: DATE, Value: 2019
Type: PERSON, Value: | Skyscanner
Type: WORK_OF_ART, Value: Flights to London
Type: GPE, Value: England
Type: MONEY, Value: 79
Type: DATE, Value: 2018
Type: GPE, Value: London
Type: ORG, Value: LON
Type: PERSON, Value: Airline Tickets
Type: GPE, Value: London
Type: ORG, Value: LON
Type: MONEY, Value: 410
Type: GPE, Value: London
Type: MONEY, Value: 369
Type: GPE, Value: London
Type: GPE, Value: London
Type: ORG, Value: LON
Type: PERSON, Value: eDreams
Type: ORG, Value: Flights to Singapore
Type: ORG, Value: SIN
Type: MONEY, Value: $384
Type: WORK_OF_ART, Value: Flights to Singapore, Singapore
Type: ORG, Value: SIN Airport
Type: MONEY, Value: 460
Type: DATE, Value: 2018
Type: MONEY, Value: 487
Type: GPE, Value: Singapore
Type: GPE, Value: Singapore
Type: ORG, Value: Singapore Airlines
Type: ORG, Value: Flights to Singapore Changi
Type: MONEY, Value: 360
Type: DATE, Value: 2019
Type: PERSON, Value: | Skyscanner
Type: WORK_OF_ART, Value: Flights to Singapore - Find Airfares to Singapore
Type: ORG, Value: Flights to Singapore Changi
Type: PERSON, Value: | Skyscanner
Type: WORK_OF_ART, Value: Flights to Singapore - Search Deals on Airfare to Singapore
Type: WORK_OF_ART, Value: Flights to Macau
Type: MONEY, Value: 404
Type: PERSON, Value: Flights
Type: GPE, Value: Macau SAR
Type: LOC, Value: Asia
Type: MONEY, Value: 158
Type: DATE, Value: 2019
Type: MONEY, Value: 464
Type: GPE, Value: Macau
Type: GPE, Value: China
Type: PERSON, Value: Flights
Type: GPE, Value: Macau
Type: GPE, Value: Macau
Type: PERSON, Value: | Skyscanner
Type: GPE, Value: Macau
Type: GPE, Value: Macau
Type: GPE, Value: Macau
Type: GPE, Value: Macau Air
Type: GPE, Value: Macau
Type: MONEY, Value: 455
Type: GPE, Value: Macau
Type: GPE, Value: Skyscanner
Type: PERSON, Value: Flights
Type: MONEY, Value: 539
Type: MONEY, Value: 367
Type: GPE, Value: Dubai
Type: GPE, Value: United Arab Emirates
Type: GPE, Value: Dubai
Type: MONEY, Value: 496
Type: GPE, Value: Dubai
Type: GPE, Value: Dubai | Emirates
Type: GPE, Value: Dubai
Type: MONEY, Value: 477
Type: DATE, Value: 2019
Type: PERSON, Value: | Skyscanner
Type: WORK_OF_ART, Value: Flights to Dubai
Type: GPE, Value: United Arab Emirates
Type: ORG, Value: DXB & DWC Airports
Type: GPE, Value: Dubai
Type: CARDINAL, Value: 208
Type: PERSON, Value: | Skyscanner
Type: WORK_OF_ART, Value: Flights to Dubai
Type: GPE, Value: United Arab Emirates
Type: GPE, Value: Dubai
Type: ORG, Value: Orbitz.com
Type: GPE, Value: Lagos
Type: GPE, Value: Dubai
Type: GPE, Value: Paris
Type: ORG, Value: PAR
Type: MONEY, Value: 257
Type: MONEY, Value: 297
Type: GPE, Value: Paris
Type: GPE, Value: France
Type: ORG, Value: PAR
Type: GPE, Value: Paris
Type: GPE, Value: Ile-de
Type: FAC, Value: CDG Airport
Type: MONEY, Value: 67
Type: DATE, Value: 2018
Type: GPE, Value: Paris
Type: GPE, Value: France
Type: GPE, Value: Paris
Type: GPE, Value: Paris
Type: MONEY, Value: 235
Type: DATE, Value: 2019
Type: PERSON, Value: | Skyscanner
Type: GPE, Value: Paris
Type: GPE, Value: France
Type: ORG, Value: Air France USA
Type: MONEY, Value: 404
Type: GPE, Value: Paris
Type: ORG, Value: PAR
Type: ORG, Value: Orbitz.com
Type: GPE, Value: Paris
Type: MONEY, Value: 15
Type: EVENT, Value: Paris Flights
Type: DATE, Value: 2019
Type: MONEY, Value: 374
Type: ORG, Value: | Travelocity
Type: GPE, Value: New York
Type: ORG, Value: NYC
Type: MONEY, Value: 83
Type: MONEY, Value: 53
Type: GPE, Value: New York City
Type: GPE, Value: New York
Type: GPE, Value: New York
Type: GPE, Value: New York
Type: MONEY, Value: 100
Type: DATE, Value: 2019
Type: GPE, Value: New York
Type: GPE, Value: New York
Type: WORK_OF_ART, Value: Book Cheap Flights To New York City
Type: GPE, Value: New York
Type: MONEY, Value: 79
Type: DATE, Value: 2019
Type: PERSON, Value: | Skyscanner
Type: GPE, Value: New York City
Type: GPE, Value: New York City
Type: MONEY, Value: 16
Type: GPE, Value: New York
Type: ORG, Value: NYC
Type: MONEY, Value: 100
Type: MONEY, Value: 118
Type: GPE, Value: New York
Type: ORG, Value: NYC
Type: GPE, Value: New York
Type: GPE, Value: Shenzhen
Type: ORG, Value: SZX
Type: MONEY, Value: $333
Type: WORK_OF_ART, Value: Flights to Shenzhen
Type: GPE, Value: Guangdong
Type: MONEY, Value: 121
Type: DATE, Value: 2019
Type: ORG, Value: Shenzhen Bao'an International
Type: MONEY, Value: 331
Type: GPE, Value: Shenzhen
Type: GPE, Value: China
Type: MONEY, Value: 457
Type: GPE, Value: Shenzhen
Type: GPE, Value: China
Type: ORG, Value: SZX
Type: MONEY, Value: 239
Type: GPE, Value: Shenzhen
Type: GPE, Value: China
Type: ORG, Value: SZX
Type: MONEY, Value: ₹ 32,041
Type: WORK_OF_ART, Value: Flights to Shenzhen
Type: MONEY, Value: 62
Type: WORK_OF_ART, Value: Flights To Shenzhen:
Type: GPE, Value: Singapore
Type: GPE, Value: Shenzhen
Type: GPE, Value: Shenzhen
Type: GPE, Value: Singapore
Type: GPE, Value: Kuala Lumpur Intl
Type: ORG, Value: KUL
Type: MONEY, Value: $360
Type: PERSON, Value: Flights
Type: GPE, Value: Kuala Lumpur
Type: MONEY, Value: 391
Type: DATE, Value: 2019
Type: MONEY, Value: 473
Type: GPE, Value: Kuala Lumpur
Type: GPE, Value: Malaysia
Type: PERSON, Value: Flights
Type: GPE, Value: Kuala Lumpur
Type: MONEY, Value: 342
Type: DATE, Value: 2019
Type: PERSON, Value: | Skyscanner
Type: PERSON, Value: Flights
Type: GPE, Value: Kuala Lumpur
Type: NORP, Value: Selangor
Type: ORG, Value: KUL Airport
Type: MONEY, Value: 369
Type: GPE, Value: Kuala Lumpur
Type: GPE, Value: Malaysia
Type: GPE, Value: Kuala Lumpur Intl
Type: ORG, Value: KUL
Type: PERSON, Value: Flights
Type: GPE, Value: Kuala Lumpur - Widest
Type: PERSON, Value: Flights
Type: GPE, Value: Kuala Lumpur
Type: MONEY, Value: 44
Type: GPE, Value: Kuala Lumpur
Type: ORG, Value: Malaysia - Webjet
Type: MONEY, Value: 453
Type: GPE, Value: Phuket
Type: GPE, Value: Thailand
Type: ORG, Value: Flights to Phuket, Phuket
Type: MONEY, Value: 428
Type: DATE, Value: 2018
Type: MONEY, Value: 399
Type: WORK_OF_ART, Value: Flights to Phuket
Type: MONEY, Value: 390
Type: DATE, Value: 2019
Type: GPE, Value: Phuket
Type: GPE, Value: Phuket
Type: MONEY, Value: 282
Type: WORK_OF_ART, Value: Flights to Phuket
Type: ORG, Value: British Airways
Type: WORK_OF_ART, Value: Flights to Phuket
Type: PERSON, Value: | Skyscanner
Type: WORK_OF_ART, Value: Flights to Phuket
Type: GPE, Value: Phuket
Type: GPE, Value: New Delhi
Type: MONEY, Value: 375
Type: GPE, Value: Delhi
Type: FAC, Value: DEL Airport
Type: MONEY, Value: 393
Type: DATE, Value: 2018
Type: GPE, Value: New Delhi
Type: MONEY, Value: 367
Type: DATE, Value: 2019
Type: PERSON, Value: | Skyscanner
Type: GPE, Value: New Delhi
Type: PERSON, Value: | Skyscanner
Type: MONEY, Value: 483
Type: GPE, Value: New Delhi
Type: GPE, Value: India
Type: GPE, Value: Delhi
Type: GPE, Value: India
Type: GPE, Value: Delhi
Type: GPE, Value: Delhi
Type: MONEY, Value: 664
Type: ORG, Value: Lufthansa
Type: GPE, Value: Delhi
Type: MONEY, Value: 485
Type: GPE, Value: Delhi
Type: MONEY, Value: US$ 474
Type: GPE, Value: New Delhi
Type: PERCENT, Value: 30%
Type: ORG, Value: New Delhi Air Tickets
Type: GPE, Value: Tokyo
Type: ORG, Value: TYO
Type: MONEY, Value: 368
Type: MONEY, Value: 478
Type: GPE, Value: Tokyo
Type: GPE, Value: Japan
Type: PERSON, Value: Flights
Type: GPE, Value: Tokyo
Type: GPE, Value: Tokyo
Type: ORG, Value: HND Airport
Type: MONEY, Value: 363
Type: DATE, Value: 2018
Type: GPE, Value: Tokyo
Type: MONEY, Value: 367
Type: DATE, Value: 2019
Type: MONEY, Value: 807
Type: GPE, Value: Tokyo
Type: ORG, Value: TYO
Type: ORG, Value: Orbitz.com
Type: GPE, Value: Tokyo
Type: GPE, Value: Japan
Type: GPE, Value: Tokyo
Type: GPE, Value: Tokyo
Type: ORG, Value: TYO
Type: GPE, Value: Tokyo
Type: MONEY, Value: 411
Type: DATE, Value: 2019
Type: PERSON, Value: | Skyscanner
Type: GPE, Value: Tokyo
Type: PERSON, Value: RM992 | Skyscanner Malaysia
Type: PERSON, Value: Sydney
Type: ORG, Value: SYD
Type: GPE, Value: Tokyo
Type: WORK_OF_ART, Value: Flights to Rome
Type: MONEY, Value: 327
Type: MONEY, Value: 331
Type: GPE, Value: Rome
Type: GPE, Value: Italy
Type: PERSON, Value: Flights
Type: GPE, Value: Rome
Type: PERSON, Value: Lazio
Type: FAC, Value: FCO Airport
Type: MONEY, Value: 60
Type: DATE, Value: 2018
Type: GPE, Value: Rome
Type: MONEY, Value: 293
Type: DATE, Value: 2019
Type: PERSON, Value: | Skyscanner
Type: WORK_OF_ART, Value: Flights to Rome
Type: GPE, Value: Italy
Type: GPE, Value: Rome
Type: GPE, Value: Rome
Type: GPE, Value: Rome
Type: GPE, Value: Rome
Type: MONEY, Value: 350
Type: ORG, Value: Lufthansa
Type: ORG, Value: Rome Flights
Type: DATE, Value: 2019
Type: MONEY, Value: 326
Type: WORK_OF_ART, Value: Flights to Rome
Type: MONEY, Value: 30
Type: DATE, Value: 2019
Type: PERSON, Value: | Skyscanner
Type: FAC, Value: Flights
Type: GPE, Value: Taipei
Type: GPE, Value: Taiwan
Type: ORG, Value: TPE & TSA Airports
Type: MONEY, Value: 201
Type: DATE, Value: 2018
Type: GPE, Value: Taipei
Type: ORG, Value: Taoyuan Intl & other Airports
Type: MONEY, Value: 463
Type: GPE, Value: Taipei
Type: GPE, Value: Taiwan
Type: PERSON, Value: Flights
Type: GPE, Value: Taipei
Type: MONEY, Value: 384
Type: DATE, Value: 2019
Type: GPE, Value: Taipei
Type: GPE, Value: Taipei
Type: GPE, Value: Taipei
Type: MONEY, Value: 198
Type: ORG, Value: | Skyscanner Singapore
Type: GPE, Value: Taipei
Type: ORG, Value: Singapore Airlines
Type: GPE, Value: Taipei
Type: ORG, Value: RM455 | Skyscanner
Type: MONEY, Value: 412
Type: GPE, Value: Los Angeles
Type: GPE, Value: Taipei
Type: ORG, Value: Orbitz.com
Type: GPE, Value: Taipei
Type: MONEY, Value: 414
Type: DATE, Value: 2019
Type: PERSON, Value: | Skyscanner
Type: FAC, Value: Flights
Type: GPE, Value: Guangzhou
Type: GPE, Value: Guangdong
Type: MONEY, Value: 348
Type: DATE, Value: 2019
Type: PERSON, Value: Flights
Type: GPE, Value: Guangzhou
Type: MONEY, Value: 322
Type: MONEY, Value: 443
Type: GPE, Value: Guangzhou
Type: GPE, Value: China
Type: PERSON, Value: Flights
Type: GPE, Value: Guangzhou
Type: GPE, Value: China
Type: PERSON, Value: Flights
Type: GPE, Value: Guangzhou
Type: MONEY, Value: 356
Type: DATE, Value: 2019
Type: PERSON, Value: | Skyscanner
Type: FAC, Value: Flights
Type: GPE, Value: Guangzhou
Type: MONEY, Value: 331
Type: PERSON, Value: | Skyscanner
Type: PERSON, Value: Flights
Type: GPE, Value: Guangzhou
Type: GPE, Value: Malaysia
Type: GPE, Value: Guangzhou
Type: MONEY, Value: 345
Type: GPE, Value: Guangzhou
Type: DATE, Value: 2018
Type: WORK_OF_ART, Value: - Book Now | Expedia
Type: PERSON, Value: Flights
Type: GPE, Value: Guangzhou
Type: ORG, Value: R8293 - Cheapflights.co.za
Type: GPE, Value: Mumbai
Type: MONEY, Value: 494
Type: PERSON, Value: Flights
Type: GPE, Value: Mumbai
Type: FAC, Value: BOM Airport
Type: MONEY, Value: 507
Type: DATE, Value: 2018
Type: GPE, Value: Mumbai
Type: MONEY, Value: 438
Type: DATE, Value: 2019
Type: MONEY, Value: 506
Type: GPE, Value: Mumbai
Type: GPE, Value: India
Type: PERSON, Value: Flights
Type: GPE, Value: Mumbai
Type: GPE, Value: India
Type: GPE, Value: Mumbai
Type: GPE, Value: Mumbai
Type: GPE, Value: Airline Tickets
Type: PERSON, Value: Flights
Type: GPE, Value: Mumbai
Type: GPE, Value: Bombay
Type: GPE, Value: Mumbai
Type: ORG, Value: R5067 - Cheapflights.co.za
Type: GPE, Value: Mumbai
Type: MONEY, Value: 676
Type: ORG, Value: Lufthansa
Type: PERSON, Value: Flights
Type: GPE, Value: Mumbai
Type: MONEY, Value: 309
Type: PERSON, Value: | Skyscanner
Type: PERSON, Value: Flights
Type: GPE, Value: Mecca
Type: GPE, Value: Saudi Arabia
Type: MONEY, Value: 242
Type: DATE, Value: 2019
Type: CARDINAL, Value: 5
Type: GPE, Value: Mecca
Type: GPE, Value: Saudi Arabia - TripAdvisor
Type: GPE, Value: Mecca
Type: ORG, Value: JED
Type: MONEY, Value: 304
Type: GPE, Value: Mecca
Type: FAC, Value: JED Airport
Type: PERSON, Value: Expedia
Type: GPE, Value: Mecca Flights
Type: DATE, Value: 2019
Type: PERSON, Value: JED Airfare
Type: MONEY, Value: 881
Type: WORK_OF_ART, Value: Flights to Makkah | Book Flights to Makkah Online - tajawal
Type: GPE, Value: Mecca
Type: MONEY, Value: 1,042
Type: GPE, Value: Mecca
Type: ORG, Value: JED
Type: ORG, Value: Orbitz.com
Type: GPE, Value: Mecca
Type: GPE, Value: Mecca
Type: GPE, Value: Mecca
Type: NORP, Value: Saudi
Type: MONEY, Value: 509
Type: GPE, Value: Istanbul
Type: GPE, Value: Turkey
Type: PERSON, Value: Flights
Type: GPE, Value: Istanbul
Type: GPE, Value: Turkey
Type: MONEY, Value: 509
Type: DATE, Value: 2019
Type: GPE, Value: Istanbul
Type: MONEY, Value: 446
Type: DATE, Value: 2019
Type: PERSON, Value: | Skyscanner
Type: ORG, Value: IST
Type: ORG, Value: İstanbul | Turkish Airlines
Type: FAC, Value: | City Guide
Type: GPE, Value: Istanbul
Type: GPE, Value: Turkey
Type: GPE, Value: Istanbul
Type: CARDINAL, Value: 492
Type: GPE, Value: Istanbul
Type: GPE, Value: Istanbul
Type: GPE, Value: Turkey
Type: GPE, Value: Istanbul
Type: MONEY, Value: 32
Type: GPE, Value: Istanbul
Type: GPE, Value: Turkey
Type: GPE, Value: Prague
Type: MONEY, Value: 371
Type: GPE, Value: Prague
Type: MONEY, Value: 386
Type: DATE, Value: 2019
Type: PERSON, Value: | Skyscanner
Type: FAC, Value: Flights
Type: GPE, Value: Prague
Type: GPE, Value: Prague
Type: FAC, Value: PRG Airport
Type: MONEY, Value: 74
Type: DATE, Value: 2018
Type: MONEY, Value: 426
Type: GPE, Value: Prague
Type: GPE, Value: Czech Republic
Type: GPE, Value: Prague
Type: GPE, Value: Ruzyne
Type: PERSON, Value: Flights
Type: GPE, Value: Prague
Type: MONEY, Value: 27
Type: PERSON, Value: | Skyscanner
Type: GPE, Value: Prague
Type: MONEY, Value: 575
Type: ORG, Value: Lufthansa
Type: DATE, Value: winter
Type: GPE, Value: Prague
Type: MONEY, Value: 23.16
Type: GPE, Value: Prague
Type: MONEY, Value: 42
Type: GPE, Value: Israel
Type: GPE, Value: Prague
Type: GPE, Value: Skyscanner
Type: GPE, Value: Miami
Type: ORG, Value: MIA
Type: MONEY, Value: 56
Type: GPE, Value: Miami
Type: GPE, Value: Florida
Type: ORG, Value: MIA Airport
Type: MONEY, Value: 56
Type: DATE, Value: 2018
Type: MONEY, Value: 97
Type: GPE, Value: Miami
Type: GPE, Value: Florida
Type: ORG, Value: MIA
Type: GPE, Value: Miami
Type: GPE, Value: Florida
Type: MONEY, Value: 61
Type: GPE, Value: Miami
Type: ORG, Value: MIA
Type: DATE, Value: 2019
Type: LOC, Value: | Hotwire
Type: GPE, Value: Miami
Type: MONEY, Value: 55
Type: DATE, Value: 2019
Type: PERSON, Value: | Skyscanner
Type: FAC, Value: Flights
Type: GPE, Value: Miami
Type: MONEY, Value: 23
Type: GPE, Value: JETCOST
Type: MONEY, Value: 132
Type: GPE, Value: Miami
Type: ORG, Value: MIA
Type: ORG, Value: Orbitz.com
Type: ORG, Value: Miami | CheapOair
Type: GPE, Value: Miami
Type: GPE, Value: FL
Type: ORG, Value: MIA
Type: MONEY, Value: 455
Type: GPE, Value: Seoul
Type: GPE, Value: South Korea
Type: ORG, Value: SEL
Type: WORK_OF_ART, Value: Flights to Seoul
Type: ORG, Value: SEL
Type: MONEY, Value: $361
Type: MONEY, Value: $923 +
Type: WORK_OF_ART, Value: Flights to Seoul
Type: ORG, Value: SEL
Type: ORG, Value: Orbitz.com
Type: GPE, Value: Seoul
Type: FAC, Value: ICN Airport
Type: MONEY, Value: 196
Type: DATE, Value: 2018
Type: WORK_OF_ART, Value: Flights to Seoul
Type: MONEY, Value: 334
Type: DATE, Value: 2019
Type: PERSON, Value: | Skyscanner
Type: WORK_OF_ART, Value: Flights to Seoul
Type: GPE, Value: South Korea
Type: GPE, Value: Seoul
Type: GPE, Value: Malaysia
Type: GPE, Value: Seoul
Type: GPE, Value: Korea
Type: LOC, Value: Delta
Type: GPE, Value: Seoul
Type: MONEY, Value: 374
Type: DATE, Value: 2019
Type: PERSON, Value: | Skyscanner
Type: WORK_OF_ART, Value: Flights to Seoul | StudentUniverse
Type: MONEY, Value: 327
Type: GPE, Value: Barcelona
Type: GPE, Value: Spain
Type: PERSON, Value: Flights
Type: ORG, Value: Barcelona-El Prat
Type: ORG, Value: BCN
Type: MONEY, Value: $255
Type: WORK_OF_ART, Value: Flights to Barcelona
Type: MONEY, Value: 244
Type: DATE, Value: 2019
Type: PERSON, Value: | Skyscanner
Type: WORK_OF_ART, Value: Flights to Barcelona
Type: GPE, Value: Catalonia
Type: FAC, Value: BCN Airport
Type: MONEY, Value: 328
Type: DATE, Value: 2018
Type: GPE, Value: Barcelona
Type: CARDINAL, Value: 23
Type: PERSON, Value: | Skyscanner
Type: PERSON, Value: Flights
Type: GPE, Value: Barcelona
Type: GPE, Value: USA
Type: GPE, Value: Canada
Type: GPE, Value: Barcelona
Type: ORG, Value: BCN
Type: MONEY, Value: 331
Type: ORG, Value: Lufthansa
Type: DATE, Value: winter
Type: GPE, Value: Barcelona
Type: MONEY, Value: 22.49
Type: ORG, Value: Barcelona - Wizz Air
Type: MONEY, Value: 371
Type: GPE, Value: Pattaya
Type: GPE, Value: Thailand
Type: WORK_OF_ART, Value: Flights to Pattaya
Type: GPE, Value: Chonburi
Type: MONEY, Value: 125
Type: DATE, Value: 2019
Type: WORK_OF_ART, Value: Flights to Pattaya
Type: MONEY, Value: 492
Type: PERSON, Value: | Skyscanner
Type: WORK_OF_ART, Value: Flights to Pattaya
Type: MONEY, Value: 308
Type: WORK_OF_ART, Value: Flights to Pattaya
Type: ORG, Value: UTP
Type: PERSON, Value: Pattaya
Type: GPE, Value: Pattaya
Type: GPE, Value: Thailand
Type: MONEY, Value: 33,681
Type: MONEY, Value: 454
Type: DATE, Value: 2019
Type: GPE, Value: | Hotwire
Type: GPE, Value: Chonburi
Type: ORG, Value: UTP
Type: WORK_OF_ART, Value: Flights to Pattaya
Type: WORK_OF_ART, Value: the Cheapest Flight to Pattaya
Type: ORG, Value: Pattaya | Expedia
Type: GPE, Value: Shanghai
Type: GPE, Value: China
Type: MONEY, Value: 153
Type: DATE, Value: 2019
Type: GPE, Value: Shanghai
Type: ORG, Value: PVG
Type: MONEY, Value: $349
Type: MONEY, Value: 407
Type: GPE, Value: Shanghai
Type: GPE, Value: China
Type: PERSON, Value: Flights
Type: GPE, Value: Shanghai
Type: MONEY, Value: 317
Type: DATE, Value: 2019
Type: PERSON, Value: | Skyscanner
Type: FAC, Value: Flights
Type: GPE, Value: Shanghai
Type: MONEY, Value: 121
Type: PERSON, Value: Shanghai Pu Dong
Type: ORG, Value: PVG
Type: GPE, Value: Shanghai
Type: GPE, Value: China
Type: PERSON, Value: Flights
Type: GPE, Value: Shanghai
Type: GPE, Value: China
Type: GPE, Value: Shanghai
Type: ORG, Value: Orbitz.com
Type: GPE, Value: Shanghai
Type: GPE, Value: RM659 | Skyscanner Malaysia
Type: PERSON, Value: Flights
Type: GPE, Value: Milan
Type: MONEY, Value: 348
Type: MONEY, Value: 438
Type: GPE, Value: Milan
Type: GPE, Value: Italy
Type: PERSON, Value: Flights
Type: GPE, Value: Milan
Type: MONEY, Value: 333
Type: DATE, Value: 2019
Type: PERSON, Value: | Skyscanner
Type: PERSON, Value: Flights
Type: GPE, Value: Milan
Type: PERSON, Value: Lombardy
Type: MONEY, Value: 57
Type: DATE, Value: 2018
Type: PERSON, Value: Flights
Type: GPE, Value: Milan
Type: MONEY, Value: 23